---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Restarting services ########################################################
#
# NOTE(mhayden): It's not possible to use systemd to restart auditd on CentOS
# since it's a special service. Using the old service scripts is required.
- name: Restart auditd
  ansible.builtin.command: service auditd restart
  changed_when: false

- name: Restart chrony
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ ssh_service }}"
    state: restarted

- name: Restart clamav
  ansible.builtin.service:
    name: "{{ clamav_service }}"
    state: restarted

# Miscellaneous ##############################################################
- name: Generate auditd rules
  ansible.builtin.command: augenrules --load
  changed_when: false
  notify: restart auditd

- name: Update grub config
  ansible.builtin.command: "{{ grub_update_cmd }}"
  changed_when: false
  when:
    - security_enable_grub_update | bool
    - grub_update_binary.stat.exists | bool
    - grub_update_binary.stat.executable | bool
  notify:
    - Set bootloader file permissions after updating grub config

# NOTE(mhayden): Running `update-grub` causes the bootloader permissions to
# change, which breaks V-38583.
- name: Set bootloader file permissions after updating grub config
  ansible.builtin.file:
    path: "{{ grub_config_file_boot }}"
    mode: "0644"

- name: Dconf update
  ansible.builtin.command: dconf update
  changed_when: false
